### ISSUE TITLE
Not all /bookshelf validateLootTables command messages are translatable

### ISSUE THREAD

**Issue by Greg-21** [Darkhax-Minecraft/Bookshelf#127]
When you type command `/bookshelf validateLootTables <mod name>` and hit Enter, the message that appears after that is showing, among others, the mod name and the number of found loot tables for it. The problem appears when you omit the mod name in the command. In this case, in the message the mod name is replaced with untranslatable "every mod".

My proposition here, if it is not too hard to implement, is to detect whether the user typed mod name or not, and if so, the following message should appear: "Found %d missing loot tables for %s.", otherwise, the following one: "Found %d missing loot tables for all mods." (or something similar). Having the entire sentence in the lang files instead of just two words will make translation easier, at least for the Polish language :)

**Comment by Darkhax** [comment]
You can now translate this using `commands.bookshelf.loot_tables.wildcard`. It will give more control over how the message is structured as well.

**Comment by Greg-21** [comment]
Thank you for the change, I'll look into the lang files in a while. And sorry for my inactivity until now.
