### ISSUE TITLE
5.3.9 Crash on Startup

### ISSUE THREAD

**Issue by Artellia** [Darkhax-Minecraft/Bookshelf#134]
Current forge for 1.15.2 crashes on launch with only Bookshelf-1.15.2-5.3.9.jar in mods folder.
[crash-2020-04-09_01.28.05-client.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/4454402/crash-2020-04-09_01.28.05-client.txt)

**Comment by Artellia** [comment]
Sorry for the earlier edit, my initial report and attached log was for 5.3.9, BUT 5.2.5 seems to have the same issue.
[crash-2020-04-09_01.33.32-client.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/4454424/crash-2020-04-09_01.33.32-client.txt)

**Comment by Artellia** [comment]
5.1.4 launches successfully.

**Comment by Darkhax** [comment]
You're using an outdated forge version.

**Comment by Artellia** [comment]
No I'm not.
<img width="446" alt="Forge is current" src="https://user-images.githubusercontent.com/63389486/78867999-b350d400-7a07-11ea-944b-49a88512c1ec.png">

**Comment by Darkhax** [comment]
3.1.0 is old, this mod requires new forge features.

**Comment by Artellia** [comment]
wut.
31.1.0 is less than two weeks old and is still the current recommended version. How is that old?

**Comment by Darkhax** [comment]
The latest version is `31.1.41`. The number at the end goes up every time forge updates. You are **41** versions behind. Furthermore, 31.1.0 came out on February 3rd 2020, which is 2 months and 6 days ago.
