### ISSUE TITLE
Sky Factory 3 rely on supporters.json

### ISSUE THREAD

**Issue by madeinqc** [Darkhax-Minecraft/Bookshelf#139]
Taken from this post:
https://forum.feed-the-beast.com/threads/skyfactory-3-404-for-bookshelf.281919/

**Title** SkyFactory 3 404 for bookshelf

**Launcher Type** Server & local

**Modpack** ftb-presents-skyfactory-3

**Modpack version** 2481284

**Have you modified the pack?** No

**Link to log file** https://paste.feed-the-beast.com/view/1c0f7fe4

Details of the issue I'm using this docker container to launch the SkyFactory 3 mod. https://hub.docker.com/r/itzg/minecraft-server/

The issue is not with the container, it's with a missing bookshelf.

```
minecraft_minecraft.1.m103vga20pfl@r510 | [22:50:10] [Server thread/ERROR] [Bookshelf]: Could not access supporter data.
minecraft_minecraft.1.m103vga20pfl@r510 | java.io.FileNotFoundException: https://raw.githubusercontent.com/Darkhax-Minecraft/Bookshelf/master/supporters.json
```

Issue could be fixed by changing the link to "https://raw.githubusercontent.com/Darkhax-Minecraft/Bookshelf/1.10.2/supporters.json".

**Comment by Darkhax** [comment]
This issue was already fixed years ago. It's a non-fatal issue but you can update the mod if it bugs you.
