### ISSUE TITLE
A wrapper for Tinkers Construct's IMC, along with metal utilities. 

### ISSUE THREAD

**Issue by darkhax** [Darkhax-Minecraft/Bookshelf#14]
After messing around with Tinkers Construct for a bit, I have written a fairly basic wrapper for it's IMC based API. I have a basic version of the wrapper, and I am planning to expand upon it with utilities for easily creating fluids, ingots, and the associated compact blocks, so that mods can easily add Tinkers Construct support for various things. I am wondering if this code should be included in Bookshelf or not. 

@iLexiconn @lclc98

**Comment by iLexiconn** [comment]
Not sure why you mentioned me, but +1 for the api. I think it's a good idea to create/expand apis for other mods. It makes the library more interesting for other devs.

**Comment by darkhax** [comment]
@iLexiconn I mentioned you in the issue, because I am interested in your opinion, I hope that's okay.

**Comment by iLexiconn** [comment]
Of course it is,  just wondering :p
