### ISSUE TITLE
Backport of injectTable to 1.14.4

### ISSUE THREAD

**Issue by puggan** [Darkhax-Minecraft/Bookshelf#140]
A request in Coins, to back-port it to 1.14.4, is not posible without also backporting the Bookshelf injectTable() to 1.14.4.
https://github.com/Darkhax-Minecraft/Coins/issues/2

**Comment by Darkhax** [comment]
I've been considering the deprecation of this method in 1.15.2 so I am not sure if back porting to 1.14.4 is a good idea. I use this method in coins to merge the coin items into the various vanilla loot tables. It's a nice feature for making the mod feel like a bigger part of the world however I don't think it's a core/essential feature and could be backported without this?

**Comment by Darkhax** [comment]
Didn't mean to close the issue. I am open to back porting this feature if it is considered essential.

**Comment by Darkhax** [comment]
Since we decided not to backport this I will close again.
