### ISSUE TITLE
Bookshelf mod crashing on startup

### ISSUE THREAD

**Issue by Ben569483** [Darkhax-Minecraft/Bookshelf#145]
Crash Report File: [crash-2020-08-31_17.35.38-client.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/5151506/crash-2020-08-31_17.35.38-client.txt)
Bookshelf mod keeps crashing when i try to open the game with it

Running
Minecraft 1.15.2 
Forge 31.2.22
Java 1.8.0_251

Installed mods:
AutoSprint
Better PVP
Bookshelf
CMDCam
collective
controllable
CreativeCore
Fullbrightnesstoggle
JEI
MixinBootstrap
OptiForge
OptiFine
WAWLA
WorldDownloader

**Comment by Darkhax** [comment]
Your crash report says the WAWLA mod is crashing because it's dependency HWYLA is missing.
