### ISSUE TITLE
Class not found err

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Bookshelf#146]
Crash Report File: [here](https://gist.github.com/OtisGoodman/508e640d0d6d587cf9d746881e929b19)
Code: [here](https://github.com/OtisGoodman/Spooky-Stuff)
Running
Minecraft 1.16.3
Forge 1.16.3-34.1.1
Java 1.8
Bookshelf 1.16.3:8.0.1

Take into consideration that this is my first time using a post 1.7.10 forge version.

**Comment by Darkhax** [comment]
You need to use fg deobf compile in the dependencies block, I would also recommend updating the MCP mappings to be the same.

https://github.com/OtisGoodman/Spooky-Stuff/blob/main/build.gradle#L71
```
compile fg.deobf("net.darkhax.bookshelf:Bookshelf-1.16.3:${bookshelf_version}")
```

MCP version is `20200916-1.16.2`

**Comment by ghost** [comment]
ok sounds good

How do I update MCP mappings?

**Comment by Darkhax** [comment]
https://github.com/OtisGoodman/Spooky-Stuff/blob/main/build.gradle#L22

**Comment by ghost** [comment]
ty man
