### ISSUE TITLE
Right click spam

### ISSUE THREAD

**Issue by joklbash** [Darkhax-Minecraft/Bookshelf#153]
Upgraded to 9.2.14 this morning and started getting right click spam on both client and server. Using Forge 35.1.3.

Reverting back to 9.1.13 stopped the spam.

[net.darkhax.bookshelf.Bookshelf:onClick:121]: java.lang.NullPointerException
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.darkhax.bookshelf.serialization.BlockIngredientSerializer.read(BlockIngredientSerializer.java:24)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.darkhax.bookshelf.serialization.BlockIngredientSerializer.read(BlockIngredientSerializer.java:11)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.darkhax.bookshelf.Bookshelf.onClick(Bookshelf.java:114)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:789)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:268)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1366)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[net.darkhax.bookshelf.Bookshelf:onClick:121]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by Darkhax** [comment]
Thank you for reporting this. I accidentally left some debug code in for the new BlockIngredient feature. The debug code has been removed and a new version should be available on CurseForge within a few minutes.
