### ISSUE TITLE
Bookshelf-1.16.5-10.0.1 is not compatible with 1.16.4, despite being marked as compatible in CurseForge

### ISSUE THREAD

**Issue by GrumpyChunks** [Darkhax-Minecraft/Bookshelf#156]
Bookshelf-1.16.5-10.0.1.jar is marked as compatible with 1.16.4 on curseforge, so is available for people to add to 1.16.4 modpacks in the various launchers that use curseforge. However, when added to a 1.16.4 version of forge, the game stops loading, stating that 1.16.5 is required for this version of bookshelf.

**Comment by Darkhax** [comment]
Thanks for reporting. The file has been updated to reflect the correct version.
