### ISSUE TITLE
[1.16.5] NPE crash that appears to involve Bookshelf or Bed Benefits

### ISSUE THREAD

**Issue by kevinnnm12345** [Darkhax-Minecraft/Bookshelf#159]
[latest (2).log](https://github.com/Darkhax-Minecraft/Bookshelf/files/5878709/latest.2.log)

**Comment by Darkhax** [comment]
This issue is from Bed Benefits. I uploaded a new version to that mod which should fix the issue. Please let me know if it works. https://www.curseforge.com/minecraft/mc-mods/bed-benefits/files/3183601
