### ISSUE TITLE
Bookshelf Mod is crashing on startup

### ISSUE THREAD

**Issue by PouncingTiger20** [Darkhax-Minecraft/Bookshelf#162]
Crash Report (I'm using Tlauncher)
[Crash.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/6270216/Crash.txt)

The game crashes on startup

Mods I use
anvil tweaks
apotheosis
apple skin
architectury
biomesoplenty
bookshelf
branders spawner mod
crayfish gun mod
cloth config
configurable cane
content tweaker
craft tweaker
create mc
cucumber library
enchantment description
fast leaf decay
fps reducer
ftb ultimine
immersive engineering
initial inventory
iron jetpacks
jei
jei tweaker
mekanism
mob grinding utils
mouse tweaks
obfuscate
open loader
optifine 1.16.5
pam's harvestcraft 2
patchouli
placebo
psi
the one probe
tl skin cape forge
HT's treechop
upstream
xaero's minimap
xaero's woldmap

**Comment by Darkhax** [comment]
This crash is not related to bookshelf. Additionally I do not provide help/support for pirated versions of the game.

**Comment by PouncingTiger20** [comment]
Thank you for your response on this issue
