### ISSUE TITLE
Crash in Server (I use MohistMC)

### ISSUE THREAD

**Issue by Switch-Back18** [Darkhax-Minecraft/Bookshelf#167]
Hello !

I have this crash with Bookshelf , do you know why ?

https://hastebin.com/ihosoxicus.rb

Thanks

**Comment by Darkhax** [comment]
Seems to be an issue with the [Blame mod](https://www.curseforge.com/minecraft/mc-mods/blame). Perhaps they're incompatible with MohistMC. 

> Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method printFailedCommandStacktrace(Lnet/minecraft/command/CommandSource;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/mojang/brigadier/StringReader;Ljava/lang/Exception;Lnet/minecraft/util/text/IFormattableTextComponent;)V in blame.mixins.json:CommandsMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap blame.refmap.json

**Comment by Darkhax** [comment]
Spoke with the Blame dev and they did some tests. Root issue is in Mohist as this issue can not be reproduced using Forge.
