### ISSUE TITLE
Unknown crash error.

### ISSUE THREAD

**Issue by MPMob** [Darkhax-Minecraft/Bookshelf#172]
I'm trying to start a new Direwolf20 1.16.5 server and the only thing that seems to crash in my eyes is Bookshelf Mod any help would be amazing thanks!
[crash-2021-07-31_21.51.04-fml.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/6911763/crash-2021-07-31_21.51.04-fml.txt)

**Comment by Darkhax** [comment]
Seems to be an issue with FTBJanitor.

**Comment by MPMob** [comment]
Any way to fix it? Do you know off?

**Comment by Darkhax** [comment]
You should report the issue to them so they can look into it. In the short term you should be able to just remove the mod, I think it's only there to help debug issues when making the pack.

**Comment by MPMob** [comment]
It's a base mod needed for other mods so that a no go on removal. I've messaged them just need to wait on a reply.
