### ISSUE TITLE
Rare Crash Report with Bookshelf 10.2.27

### ISSUE THREAD

**Issue by Meskino** [Darkhax-Minecraft/Bookshelf#173]
[crash-2021-08-07_20.35.31-fml.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/6950025/crash-2021-08-07_20.35.31-fml.txt)

**Comment by Darkhax** [comment]
Thanks for the issue report. This was fixed August 13th, just forgot to close the issue report.
