### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Baggytrousers27** [Darkhax-Minecraft/Bookshelf#174]
Bookshelf Forge 1.17.1 11.0.1
Forge 17.17.1-37.0.31(33)

Bookshelf Forge (Bookshelf Forge) has failed to load correctly java.lang.reflect.InvocationTargetException: null

[Crashlog](https://pastebin.com/e00acDbJ).

**Comment by Darkhax** [comment]
This is caused by a breaking API change in Forge. The new [11.0.2](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/3424670) release has been updated to account for this. Old versions of Forge for 1.17.1 are now incompatible.

**Comment by miguelBL967** [comment]
MysticalAgriculture-1.18.2-5.1.3.jar
 forge 1.18.2 - 40.2.9
MysticalAgriculture (MysticalAgriculture) has failed to load correctly java.lang.reflect.InvocationException: null

**Comment by Darkhax** [comment]
@miguelBL967 That error clearly says MysticalAgriculture. This is the page for Bookshelf.

**Comment by miguelBL967** [comment]
mais e um erro

**Comment by miguelBL967** [comment]
?

**Comment by miguelBL967** [comment]
![Captura de Tela (88)](https://github.com/Darkhax-Minecraft/Bookshelf/assets/135736221/c3b15938-e155-47ab-ad54-b431da72f5ce)( e isso que aparece
