### ISSUE TITLE
Failure to Load

### ISSUE THREAD

**Issue by Nitrolysis** [Darkhax-Minecraft/Bookshelf#175]
*Edited as the wrong crash log was uploaded*
[crash-2021-09-14_20.22.54-fml.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/7164622/crash-2021-09-14_20.22.54-fml.txt)

**Comment by Darkhax** [comment]
This has nothing to do with Bookshelf or any of my mods. 

> 	Failure message: Mod roughlyenoughitems requires cloth-config 4.11.18 or above
		Currently, cloth-config is not installed

**Comment by Nitrolysis** [comment]
I apologise, it seems I attached the wrong crash log, it has been edited with the correct one.
