### ISSUE TITLE
Forge Update Problem

### ISSUE THREAD

**Issue by Xenavex** [Darkhax-Minecraft/Bookshelf#176]
There Is a Problem In the updates Which Shows That the Mod has a newer version of the current mod [1.16.5 ]
but when when checked on site it doesn't show anything 
i use 1.16.5 and this is the problem
pls do fix it :D

**Comment by Darkhax** [comment]
The latest version for 1.16.5 is 10.2.28, when using this version I do not see the update notification. I am guessing you missed that version when you looked on the website. https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/all?filter-status=1&filter-game-version=2020709689%3A8203
