### ISSUE TITLE
Console Spam and Unplayable

### ISSUE THREAD

**Issue by ReportBot9009** [Darkhax-Minecraft/Bookshelf#18]
Hey Darkhax!

Firstly, thank you so incredibly much for taking the reigns of this mod. Not five minutes ago I noticed a new download for it and I was so excited! Thank you thank you!

Now with the problem:

I loaded up my modded Minecraft and immediately noticed the 0 FPS and game spike every 3 seconds. The game would freeze for 3 seconds then let up. This went on ad infinitum.

There was no crash however, but the MultiMC console log spammed this: [16:19:48] [Client thread/WARN] [Bookshelf]: The ASM has not been initialized, there is an error with your setup!

Not sure what it is, but it is.

Do you need a modlist or anything?

Thanks again

**Comment by darkhax** [comment]
Hello, thank you for reporting this to us. It seems that for some reason the Bookshelf mod is failing to apply it's coremod. Could you please upload the entire console log, it could have some important information.

**Comment by ReportBot9009** [comment]
Do you have another site other than pastebin to upload larger files? The fml-client-latest is 57mb.

**Comment by darkhax** [comment]
Oh my, that is a terribly large file. I don't know if Gist has a file limit, however that is the text dump used by GitHub. I will only need the first 100-200 lines of the log, so that should cut down the size greatly. I just need up to the part where the first "The ASM has not been initialized" message is printed.

**Comment by ReportBot9009** [comment]
Ok I think this is the right one: https://gist.github.com/ace80ec93b33f0488587.git

If not, I made this one: https://zerobin.net/?ef9703f30914258d#qbT1OVUemXUd+ONAB+P1m8vjQloVP+GgZmVRAcEuxTs=

**Comment by darkhax** [comment]
Thank you, we have identified the issue, and a fix is being implemented as a type this. A new build will automatically be sent to CurseForge once we update the code on GitHub.

**Comment by ReportBot9009** [comment]
Great! Thank you and have a wonderful day/evening/night wherever you are.

**Comment by darkhax** [comment]
The new build of Bookshelf has been marked as accepted on CurseForge. You can download it [here](http://minecraft.curseforge.com/projects/bookshelf/files/2268802).
