### ISSUE TITLE
Fabric 1.18.2 crash

### ISSUE THREAD

**Issue by Kuggle01** [Darkhax-Minecraft/Bookshelf#181]
I have absolutly no idea what is causing this crash exactly, this is my log https://paste.ee/p/co24r

**Comment by Darkhax** [comment]
Hello, thanks for reporting this issue. You should be able to use the previous version without issues while I investigate this.

**Comment by Darkhax** [comment]
I've now released version 13.0.10 which should fix your issue. Could you please download the update and let me know if the fix works for you? https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/3740884

**Comment by Kuggle01** [comment]
No longer crashes, thanks for the Quick fix

**Comment by Sunconure11** [comment]
I'm still encountering this
