### ISSUE TITLE
Bookshelf-Forge-1.18.2-13.2.22 Crash on start

### ISSUE THREAD

**Issue by Smokie233** [Darkhax-Minecraft/Bookshelf#187]
I updated to the newest version [Bookshelf-Forge-1.18.2-13.2.22.jar] and it crashes on startup with exit code -1.  I then put the old jar [Bookshelf-Forge-1.18.2-13.2.21.jar] back in and MC starts up no problem.

**Comment by Darkhax** [comment]
Please include your crash log.

**Comment by gchpaco** [comment]
This happened to me with the following log; there is no actual crash report. https://gist.github.com/gchpaco/b72c414bd158ba8301e4d742e8fdb171

**Comment by gchpaco** [comment]
Forge 40.1.25

**Comment by Darkhax** [comment]
Thanks for the crash log. It looks like there was an issue with how these updates were compiled. I've pulled them from CurseForge for now.
