### ISSUE TITLE
1.19 Latest Forge Crash

### ISSUE THREAD

**Issue by MianReplicate** [Darkhax-Minecraft/Bookshelf#191]
Currently Bookshelf crashes on the latest versions of Forge upon startup.

Minecraft Version: 1.19
Forge Version: 41.0.94
Mod Version: 14.0.3

Crash Log: https://mclo.gs/xRPiavw

**Comment by Darkhax** [comment]
Hello, this is a broader issue caused by Forge making breaking changes to their APIs mid-version. Many mods including Bookshelf will need to update to account for these changes. They only made these changes 5 hours ago, so mod authors will need some time to update everything.

**Comment by Darkhax** [comment]
The [14.1.7](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/3871514) release of Bookshelf should be compatible with your version of Forge. I will make my way through the rest of my mods this week.
