### ISSUE TITLE
Multiplayer menu says incompatible with forge server

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Bookshelf#192]
please make this not required on server-side its confusing for clients trying to join a forge server to be told its incompatible

[12Jul2022 22:30:28.751] [Netty Client IO/INFO] [net.minecraftforge.client.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [bookshelf]

**Comment by Darkhax** [comment]
There are many cases where Bookshelf is required on both sides, this is mainly the case for mods that add new content to the game like Dark Paintings, Dark Utilities, etc. 

In 14.2.10 I've told forge to ignore the version, but it is still highly recommended as some bookshelf features may not work as expected. https://github.com/Darkhax-Minecraft/Bookshelf/commit/6afe1bc3c6d35ba3271feeba59d841bf84cc7f78
