### ISSUE TITLE
Crash upon opening (1.19)

### ISSUE THREAD

**Issue by lenamars** [Darkhax-Minecraft/Bookshelf#196]
Hello, I'm having a pretty bad issue with this mod. Minecraft won't even open for me, and I've narrowed it down to this mod causing the issue (I believe, it's either this or Enchantment Descriptions). I use Forge 41.1.0 and have tried using your latest and next to latest version to no avail. Please please help!

**Comment by Darkhax** [comment]
Hello, please upload your log file so I can see why it is crashing.

**Comment by lenamars** [comment]
[latest.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/9237406/latest.log)
Is this it?

**Comment by Darkhax** [comment]
Yes that is the correct file. You are playing 1.19 but have Bookshelf for 1.19.1 installed. Try this file instead. https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/3901609

**Comment by lenamars** [comment]
Oh my gosh! I am so so sorry for taking up your time, also you're a real one bro, ur mods are awesome. Thank you so much!
