### ISSUE TITLE
Link in README is broken.

### ISSUE THREAD

**Issue by furrz** [Darkhax-Minecraft/Bookshelf#200]
There is a broken link in the README linking to https://maven.mcmoddev.com/net/darkhax/.  You may want to update this to link to the current repository at https://maven.blamejared.com/net/darkhax/bookshelf/.

(Might also want to document inclusion in Fabric mods while you're at it?)

**Comment by Darkhax** [comment]
Thanks for letting me know. I've updated the info now in https://github.com/Darkhax-Minecraft/Bookshelf/commit/8496a8dc386737d5a6e0d1fc7ba584241b68dcc1
