### ISSUE TITLE
Bookshelf 1.18.2 version 13.2.50 says that have a new version

### ISSUE THREAD

**Issue by tabr** [Darkhax-Minecraft/Bookshelf#204]
But there is no new version for 1.18.2

**Comment by Darkhax** [comment]
Hello, version 13.2.51 was released two days ago. You can find all the official 1.18.2 files [here](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/all?filter-status=1&filter-game-version=2020709689%3A9008).
