### ISSUE TITLE
Mixin Error while starting

### ISSUE THREAD

**Issue by Kapitencraft** [Darkhax-Minecraft/Bookshelf#206]
Well, the crash report should speak for it self
[crash_report.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/10347838/crash_report.txt)

**Comment by Darkhax** [comment]
Hello, it looks like you are trying to use Bookshelf in a development environment without Mixin remapping enabled. This is required to load mixins using your development mappings of choice. You can see an example of this [here](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/1.19.2/Forge/build.gradle#L35-L36).

**Comment by Kapitencraft** [comment]
It appears that is not all, there is a new error: 
[crash_report.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/10354835/crash_report.txt)

**Comment by Darkhax** [comment]
Mod dependencies on Forge need to be deobfuscated for development environments. You should also be using the maven and not a mods folder on your system.

```groovy

repositories {
    maven { 
      url 'https://maven.blamejared.com' 
    }
}

dependencies {

    implementation fg.deobf("net.darkhax.bookshelf:Bookshelf-Forge-1.19.3:17.0.2")
}
```
