### ISSUE TITLE
Bookshelf Not Playing Nice with Other Mods

### ISSUE THREAD

**Issue by koorbmeh** [Darkhax-Minecraft/Bookshelf#21]
Bookshelf appears to be preventing the Ultimate Unicorn Mod from working correctly.  Trying to put Enchanting Plus and Ultimate Unicorn Mod together in same mod pack.

**Comment by darkhax** [comment]
What do you mean by not playing nicely? If there is a crash, we will need crash logs.

**Comment by LemADEC** [comment]
Logs or it didn't happen

**Comment by darkhax** [comment]
Please provide more info for this issue. Until then it is invalid.
