### ISSUE TITLE
1.19.2 - Bookshelf Cripples ``domum_ornamentum-1.19-1.0.83-ALPHA-universal.jar`` + ``rubidium-0.6.2.jar`` via bad interactions.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Darkhax-Minecraft/Bookshelf#210]
Please see gathered data. 
https://github.com/P3rf3ctXZer0/P3rf3ctXZer0s-Workshop/issues/1

**Comment by Darkhax** [comment]
Are you able to recreate this issue using only the mods listed? What blocks are rendering invisible, and are they always invisible or only invisible when placed?

I tried
- Forge 43.2.0
- Bookshelf 16.2.17
- Rubidium 0.6.2
- Domum Ornamentum 1.0.83

![image](https://user-images.githubusercontent.com/2250798/223106592-b55c1004-c138-47a4-ab58-53021bea8235.png)

**Comment by Darkhax** [comment]
Adding another mod that uses Bookshelf's code to set render layers such as Dark Utilities does seem to cause this issue, but only when Rubidium is installed. I will look into this more closely soon.

**Comment by P3rf3ctXZer0** [comment]
> Adding another mod that uses Bookshelf's code to set render layers such as Dark Utilities does seem to cause this issue, but only when Rubidium is installed. I will look into this more closely soon.

I didn't realize that was another prereq; good to know I will add that to my data. I was not about to tear the pack apart a 10th time that day. Glad you could follow my bread crumbs. That makes sense though ... hm.

**Comment by Darkhax** [comment]
This should be fixed in the [new alpha](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/4426591) of bookshelf. Please let me know if this works or if you run into any related issues.

**Comment by P3rf3ctXZer0** [comment]
If you don't mind me asking what did you change so I can index it in case other mods suffer the same issue?

**Comment by Darkhax** [comment]
I was setting the block render layer during Forge's block registration event. The fix was moving it to the FMLClientSetupEvent and enqueing to the render thread. The exact commit can be found here: https://github.com/Darkhax-Minecraft/Bookshelf/commit/365b6e42c758bdd0ce93d62432460cd1d3a8c1a7
