### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by MythicalFrosdy** [Darkhax-Minecraft/Bookshelf#212]
As the title says, when Bookshelf is installed, it crashes the server on startup. Any idea why this might be happening?
Here's also the crash log. (When installed on the client, it works fine)

[latest.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/11053612/latest.log)

**Comment by Night-Sky1970** [comment]
i got the same problem.. log looks also same.. it says it wont work in a server envirment..

**Comment by Darkhax** [comment]
Thanks for letting me know about this issue. This should now be fixed in [18.0.2](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/4454754).
