### ISSUE TITLE
Unknown Recipe Serializer

### ISSUE THREAD

**Issue by collin-42** [Darkhax-Minecraft/Bookshelf#213]
Getting a connection error once adding a mod and trying to start up the server.

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentExceptionL Unknown recipe serializer bookshelf:shapeless_durability

**Comment by Darkhax** [comment]
Make sure the client and server both have Bookshelf installed. If this doesn't fix the issue, please include the full log.
