### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by SorkoPiko** [Darkhax-Minecraft/Bookshelf#215]
Hey, could you add this mod to Modrinth? I get most of my mods from there, as they have a better api, and I would appreciate if this mod was on there too. You have an account, but you've only posted one mod. If it's not possible, no need to worry. Thanks!

**Comment by Darkhax** [comment]
Yeah, I have been working with their team to mirror my projects there. It took them a while but the finished it the other night. https://modrinth.com/mod/bookshelf-lib

**Comment by SorkoPiko** [comment]
Thanks!
