### ISSUE TITLE
update to 1.20.1

### ISSUE THREAD

**Issue by surfishs** [Darkhax-Minecraft/Bookshelf#217]
update to 1.20.1

**Comment by OBS3SS1ON** [comment]
- Replace mod 'Bookshelf' (bookshelf) 19.0.15 with any version that is compatible with:
		 - minecraft 1.20.1

**Comment by Darkhax** [comment]
An update is coming soon. GitHub is for reporting bugs or errors, not asking for updates.

**Comment by f3n3k** [comment]
> An update is coming soon. GitHub is for reporting bugs or errors, not asking for updates.

Totaly wrong...

> * Replace mod 'Bookshelf' (bookshelf) 19.0.15 with any version that is compatible with:
>   - minecraft 1.20.1

Interesting reply lol
