### ISSUE TITLE
Error when using this mod on LAN server

### ISSUE THREAD

**Issue by DarkFireNinja** [Darkhax-Minecraft/Bookshelf#223]
When i try to use this mod on a LAN server with my brother who doesn't have the mod installed (he is using Vanilla Minecraft), he gets this error when he tries to join my world:

**Connection Lost

Unsupported (vanilla?) client!
This server requires modded client to join!**

I'm using Quilt Loader on version 1.20.1 of Minecraft.

**Comment by Darkhax** [comment]
Hello, Bookshelf makes changes on the server that require connecting clients to also have Bookshelf installed. When you enable LAN mode you are effectively turning your client into a server and these mods will be required by all players to join.

**Comment by YoshiRulz** [comment]
At least with Fabric, it's only these:
```
[13:16:35] [Render thread/ERROR]: Registry entry (bookshelf:font) is missing from local registry (minecraft:command_argument_type)
[13:16:35] [Render thread/ERROR]: Registry entry (bookshelf:item_output) is missing from local registry (minecraft:command_argument_type)
```
And vanilla clients can join fine, it's only clients *with Fabric API but without Bookshelf* which get an error.
