### ISSUE TITLE
[BUG] (/bookshelf font book) Not working

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Bookshelf#225]
### Minecraft Version

1.20.4

### Mod Version

23.0.5

### Mod Loader

Forge

### What environment are you running the mod in?

Don't Know / Not Applicable

### Issue Description

I am trying to change the text of a book into [Runelic](https://www.curseforge.com/minecraft/mc-mods/runelic) or [Pigpen](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher) , but nothing changes other than the items name.

**Comment by Darkhax** [comment]
Thanks for reporting this. I've released [23.0.6](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/5164079) which fixes this issue. The file is currently being processed by CurseForge so it will take a few minutes for the link to work.
