### ISSUE TITLE
[BUG] Outdated structure (empty.nbt)

### ISSUE THREAD

**Issue by Linguardium** [Darkhax-Minecraft/Bookshelf#226]
### Minecraft Version

1.20.1

### Mod Version

20.1.9

### Mod Loader

Fabric

### What environment are you running the mod in?

All

### Issue Description

probably a non-issue but empty.nbt is outdated. any attempts to load it will cause DFU to load and process it. please update its version with your mc version as you update your mod.

**Comment by Darkhax** [comment]
I've pushed updates for 1.20.1 and 1.20.4 that should resolve this. What brought this issue to your attention?

**Comment by Linguardium** [comment]
discussing ram issues and the requirement for packs to have modernfix came up. figured it was time to actually report all the outdated stuff instead of forcing people to use another mod to fix an oversight

**Comment by Darkhax** [comment]
Interesting, I guess that makes sense. Thanks for filling me in.
