### ISSUE TITLE
[QUESTION] Strange behavior regarding edited menu buttons

### ISSUE THREAD

**Issue by Gronglegrowth** [Darkhax-Minecraft/Bookshelf#227]
### Question

I'm working on a modpack on fabric 1.19.2, and I noticed that, when Bookshelf is **not** present in the modlist, certain buttons on the title screen from certain mods get duplicated (I use FancyMenu for customization of their positions, and these duplicates appear in the original positions). However, when it **is** in the modlist, these duplicates are gone.

I'm very confused as to why this could be, as a quick glance through Bookshelf's source doesnt' seem to suggest that it could do anything like this. I wanted to remove Bookshelf as I no longer need it in the modpack, but because it happens to somehow fix this problem,,,,,

**Comment by Darkhax** [comment]
Hello, you're right that Bookshelf has nothing that would cause this. It sounds like FancyMenu or one of your other mods have a bug and you should report it to them.
