### ISSUE TITLE
[QUESTION] <Are there any updates planned for 1.21?>

### ISSUE THREAD

**Issue by HYDeath** [Darkhax-Minecraft/Bookshelf#229]
### Question

As the title suggests, are there any plans to update to 1.21? I'm still looking forward to the update .

**Comment by Darkhax** [comment]
Hello, yes there will be a 1.21 update but I do not have an ETA on it yet. Here is the statement from my Discord.

![image](https://github.com/Darkhax-Minecraft/Bookshelf/assets/2250798/9400aab3-afc5-430b-b5d1-668fbc8cc031)
