### ISSUE TITLE
1.21 update please

### ISSUE THREAD

**Issue by EGOIST1372** [Darkhax-Minecraft/Bookshelf#231]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Feedback

please update to 1.21
thanks <3

**Comment by Darkhax** [comment]
It's in the works but it will take a bit. This is my statement on 1.21 from Discord. 
![image](https://github.com/user-attachments/assets/fdb4799f-e96b-42cd-b66d-424ab721fbdc)
