### ISSUE TITLE
Crash on startup! 1-22-2016

### ISSUE THREAD

**Issue by DPxKnightxZero** [Darkhax-Minecraft/Bookshelf#26]
Crashlog -> https://gist.github.com/DPxKnightxZero/f4466882004edc325034

Full Crash Log -> https://gist.github.com/DPxKnightxZero/e6b027bd3d3e0fece4dd

**Comment by darkhax** [comment]
There is another mod conflicting with the potion feature. You can disable this feature in the config file.

B:potionDetectionEnabled=true 
becomes
B:potionDetectionEnabled=false
