### ISSUE TITLE
Crash on Startup 

### ISSUE THREAD

**Issue by nikkimas** [Darkhax-Minecraft/Bookshelf#27]
Hi, when I start my game with Bookshelf it crashes(does not look like the potion error).
The thing is, it only crashes on my Laptop, yes I tried different java versions :).

Here the Crash:
    http://pastebin.com/iDXjGEyG

P.S.: Sorry if it's not bookshelf causing it. I'm very bad at crash-report reading!

**Comment by darkhax** [comment]
This is an issue with the [Bookshelf API](http://minecraft.curseforge.com/projects/bookshelf-api-library) which is completely unrelated to this Bookshelf project.
