### ISSUE TITLE
[1.9] Client crash upon start

### ISSUE THREAD

**Issue by Xiaminou** [Darkhax-Minecraft/Bookshelf#30]
Crash Report: http://pastebin.com/6JR38RSz

**Comment by lclc98** [comment]
There are two mods with the name Bookshelf, this Bookshelf project is unrelated to the one that the crash is caused by, You can see the other project [here](https://github.com/TeamBR-Modding/Bookshelf) instead.

**Comment by Xiaminou** [comment]
my bad, sorry.
