### ISSUE TITLE
bookshelf 1.2.0.246 crashes dedicated forge server 1.9 build 1907 on startup 

### ISSUE THREAD

**Issue by kreezxil** [Darkhax-Minecraft/Bookshelf#32]
Issue: bookshelf 1.2.0.246 crashes dedicated forge server 1.9 build 1907 on startup -- seems it didn't care that you made it compat with 1.9.0

crash report:
https://gist.github.com/fd9adeb25c6db82e4112346bc82fc617

fml server latest:
https://gist.github.com/007fd4b58ea9e5de75377c1c22b371a5

**Comment by darkhax** [comment]
This version was created as part of a pull request from another developer, they forgot to change the name version of the mod so it shows as 1.9 in the name. Coincidentally the MCP site was having some outages so further updates could not be made to fix the issue. The build you are using is for 1.9.4 not 1.9.
