### ISSUE TITLE
Bookshelf-1.9.4-1.2.1.251 crashes client on joining SSP generated world with previous version.

### ISSUE THREAD

**Issue by kreezxil** [Darkhax-Minecraft/Bookshelf#34]
crash report
http://pastebin.com/ViRfR0je

**Comment by iLexiconn** [comment]
Update JEI or downgrade Bookshelf

**Comment by darkhax** [comment]
This is bug with Dark Utilities, not Bookshelf. It was fixed in the latest update. 95a2b095acb393f7d75518e2a6cd9792996be8ec
