### ISSUE TITLE
Bookshelf crash in SSP world load. New world not previously generated. 

### ISSUE THREAD

**Issue by Gunner76th** [Darkhax-Minecraft/Bookshelf#35]
When starting "All the Mods" version 0.0.0.9 from Curse with Bookshelf 1.9.4-1.2.1.251 loaded, JEI failes to start. As per your post for issue #34 the most recent version of JEI is being used. 
This is the crash report generated: http://pastebin.com/t3Lp3aNw

If version 250 of Bookshelf is used, The world loads with no issues. It would appear that there is a bug within the most recent release of Bookshelf causing a crash against the most recent release of JEI.

**Comment by iLexiconn** [comment]
Looks like the latest version of JEI isn't updated to the latest version of Bookshelf. You have to downgrade Bookshelf for Minecraft to work.

**Comment by Gunner76th** [comment]
Downgrading to a previous version of JEI is not possible as the previous version is compiled against 1.9.0 which will not work with the changes in forge that occurred at 1.9.4. 

I am linking/cross posting this thread to the JEI github so that they can work to resolve the issue.

**Comment by iLexiconn** [comment]
It's the JEI module 'moreoverlays' causing the crash, not JEI itself.

**Comment by mezz** [comment]
JEI and MoveOverlays have nothing to do with it.
The crash is very clear here:
```
Caused by: java.lang.NoClassDefFoundError: net/darkhax/bookshelf/lib/util/Utilities
    at net.darkhax.darkutils.items.ItemBlockCake.func_77624_a(ItemBlockCake.java:36)
```

DarkUtilties requires an outdated Bookshelf, here is the proof:
https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/master/build.gradle#L67

The issue belongs here: 
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues

**Comment by iLexiconn** [comment]
Rofl, I can't read crash logs. Sorry.

**Comment by darkhax** [comment]
Yes, a new update for DarkUtilieis is in the work. I have also been forgetting to set the minimum Bookshelf version in the DarkUtilities file. Fix is already done on my local copy.

**Comment by darkhax** [comment]
This is fixed in latest build of Dark Utilities. 95a2b095acb393f7d75518e2a6cd9792996be8ec
