### ISSUE TITLE
Crash on server forge

### ISSUE THREAD

**Issue by Tander** [Darkhax-Minecraft/Bookshelf#39]
server forge-1.9.4-12.17.0.1965
http://pastebin.com/kZyChRmy

**Comment by darkhax** [comment]
I can not confirm this using the latest Bookshelf. Could you update and try again?

**Comment by Tander** [comment]
It is the lastest release Bookshelf on Curse. Should I try alpha?

**Comment by Tander** [comment]
Ok, alpha is working fine, but I hope you'll publish stable version without this bug soon.
