### ISSUE TITLE
Crash with latest SpongeForge on server

### ISSUE THREAD

**Issue by knoxhack** [Darkhax-Minecraft/Bookshelf#40]
https://gist.github.com/knoxhack/cc8333db2c1fd10ca7dec4bb33178b9b

Reported to the SpongeForge team also.

**Comment by iLexiconn** [comment]
Has nothing to do with SpongeForge, try the latest alpha of Bookshelf. (see https://github.com/Darkhax-Minecraft/Bookshelf/issues/39)

**Comment by darkhax** [comment]
Has nothing to do with Sponge or Forge. Please use latest bookshelf.
