### ISSUE TITLE
[1.10.2] Crash when using Bookshelf *.322 with latest forge

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/Bookshelf#48]
Crash report @ http://pastebin.com/gsUUueis

When downgrading to the previous version of Bookshelf the crash becomes https://github.com/Epoxide-Software/Surge/issues/8

**Comment by Morpheus1101** [comment]
Tested using latest version of Bookshelf *.324 and same crash persists...note that this only occurs in SMP side of things, it loads an creates/joins a SP instance quite fine.

**Comment by darkhax** [comment]
You should have mentioned the SMP thing first. That's the cause of this crash, client code being executed on the server.

**Comment by Morpheus1101** [comment]
Apologies ohh wise one :P

**Comment by darkhax** [comment]
Lol, no need to apologies. I should have noticed that this was a server from the crash log, however the link with Surge (a currently client side mod) threw me off. Thanks for reporting though.
