### ISSUE TITLE
[Suggestion] getView method in net.darkhax.bookshelf.client.event.RenderItemEvent

### ISSUE THREAD

**Issue by p455w0rd** [Darkhax-Minecraft/Bookshelf#49]
**Goal:** To be able to retrieve where the item is being rendered so we can render accordingly
**Views Needed:**
- 1st Person (left hand)
- 1st Person (right hand)
- 3rd Person (left hand)
- 3rd Person (right hand)
- head (i presume like the pumpkin mask)
- gui (inventory slot)
- fixed (frames)
- ground

**Return Type:** ItemCameraTransforms._TransformType_ 

Below is an image where it looks how I want it to in 1st person and 3rd, but not in the slot. I have no way (that I'm aware of) to be able to independently translate the item when it's in the slot.
![Incorrect Item Rendering](http://image.prntscr.com/image/57ede452674f40fba45b1d5eabb38378.png)

**Comment by darkhax** [comment]
Unfortunately I don't believe it is possible to get this information without a complete rewrite of the system, as vanilla's own items don't have access to this. I may be able to make a system that circumvents vanilla rendering entirely but that would have undesirable effects.
