### ISSUE TITLE
[1.10.2] Client Crash When loading Pack with Bookshelf

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/Bookshelf#50]
Forge *.2095
Bookshelf-1.10.2-1.4.2.327
Server loads up fine however loading client does not crash log @ http://pastebin.com/0xqJXBxP

**NOTE** Bookshelf *.326 works perfectly fine

**Comment by lclc98** [comment]
Includes Gyth 1.10.2-2.0.0.14

**Comment by darkhax** [comment]
This is an issue with Gyth. It has not yet updated to support this new version. I would assume Password's Things also needs an update.

**Comment by darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/GYTH/commit/e83a38e370a1621a33a41a511a586c2a53bb4ca1
