### ISSUE TITLE
[1.10.2] Client crash at startup

### ISSUE THREAD

**Issue by kwpugh** [Darkhax-Minecraft/Bookshelf#51]
Forge: 2095
Mod: Bookshelf-1.10.2-1.4.2.327.jar

crash report: https://gist.githubusercontent.com/kwpugh/a2e0f92eca95ff010bc6f72223d33ad2/raw/cdfe4becf8004699991a0ac98366b2fe9c7a4788/bookshelf

**Comment by kwpugh** [comment]
Tried with forge 2098 and 2099, same result

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/Darkhax-Minecraft/Bookshelf/issues/50. Update GYTH :)
