### ISSUE TITLE
net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:293)

### ISSUE THREAD

**Issue by Boomflex** [Darkhax-Minecraft/Bookshelf#56]
http://pastebin.com/fJkV94Zx

I am part of the Official All the Mods server and our players keep getting the same crash in roughly the same place. No idea why though? It affects users with and without Optifine and with and without FoamFix.

It seems to be a bookshelf render issue?

**Comment by darkhax** [comment]
Do you happen to have CodeChickenLib also installed?

**Comment by Boomflex** [comment]
Any update on this, it is still happening daily.

**Comment by darkhax** [comment]
This is also an issue with CCL. The two of us are going to look into it.

**Comment by darkhax** [comment]
It seems this issue is caused by trying to render a null/invalid tcon pickaxe. In the situation described by this crash only the vanilla code is being executed here.

**Comment by Baughn** [comment]
http://pastebin.com/2LKsswda

Here's another one. Looks pretty similar, but it's a different item.

**Comment by darkhax** [comment]
@Baughn in your situation it's the `com.rwtema.extrautils2.items.ItemBlockPlantable@1e3581` which is causing the issue. As far as I can tell, Bookshelf and CCL have nothing to do with this crash.

**Comment by Baughn** [comment]
Hmm. Don't think I can do that, sorry; I wouldn't be able to remove those without thoroughly corrupting the world state.

Bookshelf is at the top of the non-Mojang stack trace, which is why I reported it here.

**Comment by darkhax** [comment]
As noted by the TCon devs, this issue is with Mekanism and not Bookshelf.
