### ISSUE TITLE
Crashing on Client world load and server startup

### ISSUE THREAD

**Issue by zombiex227** [Darkhax-Minecraft/Bookshelf#6]
---- Minecraft Crash Report ----
// My bad.

Time: 10/24/15 8:46 AM
Description: Ticking entity

java.lang.NoSuchFieldError: vanillaVillagers
	at net.darkhax.bookshelf.util.Utilities.<clinit>(Utilities.java:632)
	at net.darkhax.bookshelf.handler.ForgeEventHandler.onEntityUpdate(ForgeEventHandler.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_207_ForgeEventHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1001)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.darkhax.bookshelf.util.Utilities.<clinit>(Utilities.java:632)
	at net.darkhax.bookshelf.handler.ForgeEventHandler.onEntityUpdate(ForgeEventHandler.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_207_ForgeEventHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1001)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: EntityHorse (net.minecraft.entity.passive.EntityHorse)
	Entity ID: 2663
	Entity Name: Donkey
	Entity's Exact location: 279.36, 67.00, -137.52
	Entity's Block location: World: (279,67,-138), Chunk: (at 7,4,6 in 17,-9; contains blocks 272,0,-144 to 287,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 626 Drop: 0
	Level seed: -7970208177101388888
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (248,64,4), Chunk: (at 8,4,4 in 15,0; contains blocks 240,0,0 to 255,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1778450 game time, 662291 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 5580 (now: false), thunder time: 5925 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3607558680 bytes (3440 MB) / 4277534720 bytes (4079 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 7 total; -Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 13, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 CoFHTweaks v1.0.0RC1 Minecraft Forge 10.13.4.1517 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	oresheepmod{v2.4} [Ore Sheep] (1.7.10-OreSheepMod-v2.4.jar) 
	UCHIJAAAA	Sentries{1.7.2} [Sentries] ([1.7.10]Sentries.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.11} [BuildCraft] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	AncientWarfare{2.4.83-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.83-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.83-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.83-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.83-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) 
	UCHIJAAAA	AncientWarfareVehicle{2.4.83-beta-MC1.7.10} [Ancient Warfare Vehicles] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.11} [BC Energy] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	IC2{2.2.780-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.780-experimental.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.306.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.306.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.11} [BC Builders] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.11} [BC Factory] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	B0bGrowsOre{2.3.1} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.3.1 for 1.7.10.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHIJAAAA	bookshelf{1.0.1.47} [Bookshelf] (Bookshelf-1.7.10-1.0.1.47.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.11} [BC Transport] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.11} [BC Silicon] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.11} [BC Robotics] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCHIJAAAA	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
	UCHIJAAAA	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UCHIJAAAA	Mystcraft{0.12.3.00} [Mystcraft] (mystcraft-1.7.10-0.12.3.00.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) 
	UCHIJAAAA	eng_toolbox{1.2.3.0} [Engineer's Toolbox] (EngineersToolbox-1.2.3.0-BETA.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) 
	UCHIJAAAA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCHIJAAAA	ImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1.jar) 
	UCHIJAAAA	InventoryPets{1.3.2} [Inventory Pets] (Inventory-Pets-Mod-1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.9} [MalisisCore] (malisiscore-1.7.10-0.12.9.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.10} [Malisis' Doors] (malisisdoors-1.7.10-1.10.jar) 
	UCHIJAAAA	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.7.10-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.0.7.1} [Minecraft Comes Alive] (MCA-1.7.10-5.0.7.1-universal.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre8.92-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8-snapshot-402.jar) 
	UCHIJAAAA	modernalchemy{Beta-1.1} [Modern Alchemy] (ModernAlchemy-1.7.10-Beta-1.1-B1.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAA	recipehandler{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) 
	UCHIJAAAA	openmodularturrets{2.1.5-184} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.5-184.jar) 
	UCHIJAAAA	OresPlus{0.7.3.41B} [OresPlus] (OresPlus-0.7.3.41B.jar) 
	UCHIJAAAA	origin{5.0.1} [Origin] (Origin-1.7.10-5.0.1.jar) 
	UCHIJAAAA	PneumaticCraft{1.11.14-136} [PneumaticCraft] (PneumaticCraft-1.7.10-1.11.14-136-universal.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.8.0} [ProjectE] (ProjectE-1.7.10-PE1.8.0.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
	UCHIJAAAA	recallstones{0.4.16} [Recall Stones] (Recall-Stones-Mod-1.7.10.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V9b.jar) 
	UCHIJAAAA	Tails{1.7.10-1.4.1a} [Tails] (Tails-1.7.10-1.4.1a.jar) 
	UCHIJAAAA	telepads{1.0.0} [Telepads] (Telepads-1.7.10 -6.jar) 
	UCHIJAAAA	TF2Dispenser{1.7.10} [TF2 Dispenser] (TF2Dispenser-1.7.10.jar) 
	UCHIJAAAA	TF2Sentry{1.7.10} [TF2 Sentry] (TF2Sentry-1.7.10.jar) 
	UCHIJAAAA	TF2Teleporter{1.7.10} [TF2 Teleporter] (TF2Teleporter-1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	ttCore{MC1.7.10-0.1.1-78} [ttCore] (ttCore-MC1.7.10-0.1.1-78.jar) 
	UCHIJAAAA	UsefulTNT{1.0} [Useful TNT] (UsefulTNT 1.7.10 V9a.jar) 
	UCHIJAAAA	gvc{0.6.1} [§aGliby's§f Voice Chat Mod] (Voice-Chat-Mod-1.7.10.jar) 
	UCHIJAAAA	weepingangels{4.0.0} [Weeping Angels] (WeepingAngels-1.7.10-4.0.0.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by darkhax** [comment]
Hello, thank you for reporting this issue. You are using the wrong version of Bookshelf. Beta builds are untested, and contain upcomming features, and may also break mods which are not updated to work with them. This is why it is recommended that you use the recommended build which is [1.1.0](http://minecraft.curseforge.com/projects/bookshelf/files/2262814).

**Comment by zombiex227** [comment]
Well, at least i found an error the this build. Still waiting for telepads to be fixed lol.

**Comment by darkhax** [comment]
Yes, this is definitely an issue in the current build. After reading into forge's documentation, it seems there was an oversight on my part, and it will be fixed within the next 5 minutes.

**Comment by zombiex227** [comment]
Cool, if you want I can test all recent builds.

**Comment by darkhax** [comment]
Sure, it will take a few minutes for this build to be uploaded and released to CurseForge. Just a note, the latest build of TelePads will almost certainly have issues with the latest build, because we restructured several classes and changed how some methods work, so you might get some field not found exceptions. If you do, comment them here anyhow.

**Comment by zombiex227** [comment]
The latest version of telepads ill use on the release of bookshelf and not the beta, Telepads were broken because of a GUI thing? something like that.

**Comment by darkhax** [comment]
I am not exactly sure what Subaraki has been doing with the latest Telepad builds. There are likely a few bugs he needs to work out. There are also some issues with dying pads only being handled client side and not saved to the server.

**Comment by zombiex227** [comment]
Dying pads? What are those?

**Comment by darkhax** [comment]
You can take any dye items, like the vanilla dyes, and right click on a pad to change its color. 

![Pads With Dyed Bases](https://pbs.twimg.com/media/CO55xQiWgAAt187.png)

![Pads With Dyed Arrows](https://pbs.twimg.com/media/CO55xWeWIAAH69Z.png)

**Comment by zombiex227** [comment]
Oh yeah, they never saved when I tried them, kept changing back upon leaving the server. But the bug only occurred when I tried teleporting with them, the bug that causes an internal server error but it doesnt actually crash.

**Comment by darkhax** [comment]
You should report these issues on their [GitHub](https://github.com/ArtixAllMighty/Telepads) page. I only have minimal involvement with the project, and almost all development is handled by Subaraki.

**Comment by zombiex227** [comment]
Yeah I sent a private message to the other guy, cant remember name, of what errors came up in the server console when I teleported, I didnt see any when I tried coloring them. He said "Thanks for the error report ! I slid it in together with the new bookshelf update that is going to come.

expect an update for telepads within the week :)"

**Comment by darkhax** [comment]
Ah, okay. That's good to here.

**Comment by zombiex227** [comment]
But what does he mean slipping it into the next bookshelf update?

**Comment by darkhax** [comment]
I think what he means, is that he fixed the issue, along side all of the bookshelf updates that have taken place. He doesn't actually have the ability to "slip" code into our project, except by official means.

**Comment by zombiex227** [comment]
There are bookshelf updates? I only see the ones after the beta, and versions that are for 1.8?

**Comment by zombiex227** [comment]
Oh it doesnt say 1.8 versions anymore, I swear I saw some though.

**Comment by zombiex227** [comment]
Version checker keeps telling me there is an update for the release version of bookshelf. The new version is 1.2.0, but I dont see any.

**Comment by darkhax** [comment]
There is another project called Bookshelf that was released after ours. I am not sure what it does, but we are not affiliated with that project in any way.

**Comment by zombiex227** [comment]
Oh, version checker is sending me to the other bookshelf, and not this one. Is that a bug?

**Comment by darkhax** [comment]
Which version checker is it that you are using? LLibrary, or a different one? Also, what is the file name of the bookshelf in your mods folder?

**Comment by zombiex227** [comment]
Its just called version checker, by dynious. and the file name of the bookshelf is Bookshelf-1.7.10-1.1.0

**Comment by darkhax** [comment]
That is very strange. Our mod currently has absolutely no support for Dynious's version checker. I assume this is some form of automatic lookup feature which scans CurseForge for updates, and it is finding the other bookshelf instead. We should report this to him.

**Comment by zombiex227** [comment]
Yeah I took out the beta after the crash and put back in the release.

**Comment by zombiex227** [comment]
Lol, its probably because of the version numbers, your latest version is 1.1.0, and its detecting a "newer" one thats 1.2.0, but its the other bookshelf

**Comment by zombiex227** [comment]
So either changing the version numbers or contacting the author might work

**Comment by zombiex227** [comment]
Maybe not, im not a modder lol

**Comment by darkhax** [comment]
I have plans to add in support for his version checker anyhow, which should override any form of auto-support he has. We are also switching to a four part release number, as seen in the beta builds.

**Comment by zombiex227** [comment]
is this support going to be a direct update one? So nobody has to go to the webpage?

**Comment by darkhax** [comment]
I normally would, however after talking with the CurseForge staff about using their site to mirror all of our builds, they asked that we not use the CurseForge site in alternative downloaders, and to try and stay away from dependency loading. So you will still need to download the updates manually.

**Comment by zombiex227** [comment]
Darn, if you have alot of mods that can get very annoying, but if you cant control it then thats that lol.

**Comment by darkhax** [comment]
I would recommend looking into the CurseLauncher then, it is what I use when I play modded MC. They have a nice system set up to browse through all the mods, and when a new update is out, it gives you a button to click, and it will update that mod for you. It also supports all of the authors, of the mods that you are using.

**Comment by zombiex227** [comment]
Do I need premium for those updates to be automatic?

**Comment by darkhax** [comment]
No, you don't need premium to use the launcher, and I don't think there are any premium specific features. If there are, you should consider writing a small mod of your own, or maybe releasing a modpack on their site. They like to give all of their content creators free premium.

**Comment by zombiex227** [comment]
That would be hard, since I have no knowledge of Java, I could learn but it would be hard. Plus Ideas of mods dont come to me, because it would probably be something that has already been made.

**Comment by darkhax** [comment]
Well you can also do other kinds of things, for example, creating a new modpack, or texture pack. There are also tons of mods which have addon systems, which don't require knowledge of java. Either way, you should be fine without doing this. I haven't noticed any premium specific features since I started using the launcher.

**Comment by zombiex227** [comment]
The problem with mod packs is that you gotta make sure everything goes hand in hand, and make sure you have permission, which is a pain in the ass, It would probably be easier just to make a mod, idk, Ill use the launcher but I might try and learn Java, if you have any places you recommend I could go that would be great.

**Comment by zombiex227** [comment]
I don`t see where It checks for curse mods, just textures.

**Comment by darkhax** [comment]
Well on CurseForge, if the mod is on CurseForge, you can use it in a CurseForge pack without getting permission, which makes it very friendly for people who want to build modpacks. You can also actually get paid for modpack downloads, which is cool. As for learning Java, I learned through trial and error, and by learning a wide range of tutorials from all over the web. And then later officially learned Java through a course offered by my school. There are a lot of great resources out there though. As for the Curse launcher, I think you may have grabbed the wrong one, I probably should have specified more. The site for the launcher I am referring to is [here](http://beta.cursevoice.com/games/minecraft)

**Comment by zombiex227** [comment]
I didnt know this launcher existed, lol.

**Comment by darkhax** [comment]
It's pretty sweet, you have access to all CurseForge mods, and all of the modpacks on CurseForge. One mod I would recommend checking out, is [CoFHTweaks](http://www.curse.com/mc-mods/minecraft/230020-cofhtweaks). It makes a few changes to how the game works, such as bringing 1.8 performance changes to 1.7.10. Not everyone needs it, but it's worth having a look at.

**Comment by darkhax** [comment]
Looks like you already have CoFHTweaks, so don't mind me :p

**Comment by zombiex227** [comment]
How do you know?

**Comment by darkhax** [comment]
It's listed in the crash log you posted above, along with all the other mods you are using.

**Comment by zombiex227** [comment]
Oh lol, you should totally add me on the launcher or steam, if you want, Could make testing easier?

**Comment by darkhax** [comment]
I don't have my own computer at the moment, it died on me, so I am trying to keep things as light as possible. However once I get a new PC, I will definitely be using it, and open to adding people.

**Comment by zombiex227** [comment]
It died? Do you know how it did?

**Comment by darkhax** [comment]
I have a few working theories. But essentially all output just stopped. It still powers on, and the LED lights still go up, but audio, video, and all ports are completely dead. It's a laptop, so I can't just replace the video card, or motherboard.

**Comment by zombiex227** [comment]
Yeah its gotta be the motherboard

**Comment by zombiex227** [comment]
Ugh, I cant set the minecraft install directory to my minecraft in my appdata folder.
