### ISSUE TITLE
Thermal Expansion/Foundation Conflict

### ISSUE THREAD

**Issue by Zeronic** [Darkhax-Minecraft/Bookshelf#63]
Bookshelf-1.10.2-1.4.4.347.
ThermalExpansion-1.10.2-5.0.4.90-universal
ThermalFoundation-1.10.2-2.0.5.81-universal

I don't know what is happening but I have traced an issue with Tar and Rosin from being used as fuel to this mod.

**Comment by darkhax** [comment]
What is the actual issue? Is it a crash? This mod doesn't do anything with fuel, which is confusing.

**Comment by Zeronic** [comment]
It make it so you can't put Tar or Rosin in to the fuel slot in furnaces or any there block that would allow you to use it as fuel. Crafting is fine still.

**Comment by darkhax** [comment]
How have you come to the conclusion that this mod is responsible for the issue? Also, are you sure this is the right repo? I do nothing even remotely related to fuel, or the mods you have mentioned. There is another mod with the same name as this one, which you may be looking for?

**Comment by Zeronic** [comment]
Process of elimination, I notice the issue after we added Dark Utilities to the modpack. Removed that mod and the issues was still there, remove Bookshelf and it removed the issue.

**Comment by KingLemming** [comment]
I'm pretty sure you can safely close this one down. I addressed a mapping issue in CoFHCore a while ago. This was *probably* it.

**Comment by darkhax** [comment]
Oh okay, thanks for the heads up.
