### ISSUE TITLE
[1.11.2] [ Forge: any ] Incorrect AO on transparrent objects.

### ISSUE THREAD

**Issue by MrGraphic** [Darkhax-Minecraft/Bookshelf#65]
Image tells it all. Comparison between two builds 371/369 :
![2017-05-18_12 29](https://cloud.githubusercontent.com/assets/4780141/26200717/6956bbfc-3bc7-11e7-95d1-0c1165f5f9ff.jpg)

**Comment by darkhax** [comment]
Thank you for reporting this issue. I definitely would have missed this on my own. I've created a fix for this issue, which is included in 376. I would appreciate it if you could download that version and confirm the issues has been fixed. One thing to note is that 376 is part of Bookshelf 2, which is a partial rewrite of the code. Any mod which depends on Bookshelf (likely just Dark Utilities) is currently not compatable with this version, and would have to be temporarily removed. I am planning to push a compatable dark utilities version soon.

**Comment by MrGraphic** [comment]
Sorry for the delay, yes that fixes issue.

**Comment by darkhax** [comment]
Okay cool, thank you for testing ^^
