### ISSUE TITLE
Minecraft crashes on startup

### ISSUE THREAD

**Issue by Luckyday84** [Darkhax-Minecraft/Bookshelf#66]
My games crashes on startup using any newer version of Bookshelf. If I use version .371 it works fine so its not a huge deal.
https://pastebin.com/RYeRJYAZ

Im on Minecraft 1.11.2
Forge 13.20.0.2304
Bookshelf 1.11.2-2.0.0.376

Thanks

**Comment by darkhax** [comment]
Hi, this issue is because you're using Bookshelf 2. Bookshelf 2 is a big rewrite which adds a bunch of bug fixes and new features for mod developers. It's still in alpha, so you shouldn't use it until a full release is pushed to curse.
