### ISSUE TITLE
mekanism and bookshelf conflict(1.11.2) casing crash on load

### ISSUE THREAD

**Issue by SDUBZ** [Darkhax-Minecraft/Bookshelf#70]
Forge:1.11.2-2314
Mek:Mekanism-1.11.2-9.3.1.305
book:Bookshelf-1.11.2-2.0.0.385.jar

Crash report: http://puu.sh/wc0Ok/b8fb84818c.txt

**Comment by darkhax** [comment]
This is an issue with Mekanism and not Bookshelf. The Mekanism devs are aware of this issue, and have already fixed it. If it's not public yet, it will be soon. https://github.com/aidancbrady/Mekanism/issues/4414
