### ISSUE TITLE
Loading Crash [1.11.2-2.0.0.385] - Mekanism Incompatibility

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Bookshelf#71]
Bookshelf Version: 1.11.2-2.0.0.385
Mekanism-1.11.2.3.1.305
MekanismGenerators-1.11.2-9.3.1.305
MekanismTools-1.11.2-9.3.1.305

Forge 13.20.0.2314

Log: https://pastebin.com/0bvQyu4K

**Comment by MokahTGS** [comment]
Is this actually a Mekanism crash?

I posted there, but was unsure.  https://github.com/aidancbrady/Mekanism/issues/4445

**Comment by thommy101** [comment]
Crash on side of Mekanism and already fixed for the next release of Mekanism.

You can close this one :)
