### ISSUE TITLE
Bookshelf/Tiny Progressions Crash

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Bookshelf#72]
https://pastebin.com/tEQzbtbs

Tiny Progressions v1.11.2-2.2.0 Hotfix
Bookshelf v387

Getting that crash.  To use the latest version of DU I need the latest Bookshelf....which crashes TP.

**Comment by darkhax** [comment]
This is an issue with Tiny Progressions. The dev of that mod is aware of the issue. Not sure if/when a fix will be released.

**Comment by MokahTGS** [comment]
Except that Dev said it was your issue.

**Comment by Kashdeya** [comment]
The Issue was in TP and has been fixed. just running some test before releasing a update.
