### ISSUE TITLE
Crash with mekanism(?)

### ISSUE THREAD

**Issue by Chromogen** [Darkhax-Minecraft/Bookshelf#77]
hey there, i had a problem when updating bookshelf. something crashing the game. all mods work fine, it is definetly bookshelf update. already tested minecraft on all mods seperate t pinpoint it.

Bookshelf-1.11.2-1.5.0.371  -> Bookshelf-1.11.2-2.0.0.388

report is this:
https://pastebin.com/LAGEb0zN

sorry that ic ant provide any more info
thx :)

**Comment by IchigoGames** [comment]
i got the same crash when i updated bookshlf

**Comment by darkhax** [comment]
Duplicate of https://github.com/aidancbrady/Mekanism/issues/4414 Issue is in Mekanism and not Bookshelf.
