### ISSUE TITLE
[1.11.2] Mekanism/Bookshelf Crash

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Bookshelf#78]
https://github.com/aidancbrady/Mekanism/issues/4489

I reported this over at the Mekanism Github but just linking it in case there is something I missed.

**Comment by thommy101** [comment]
As stated on the Mekanism github, has been reported before and it's the fault of Mekanism. 

It is fixed and will be released in the next version of Mekanism.

**Comment by darkhax** [comment]
Duplicate of https://github.com/aidancbrady/Mekanism/issues/4414 Issue is in Mekanism.
