### ISSUE TITLE
[1.11.2] Server crash with latest version of Bookshelf

### ISSUE THREAD

**Issue by kwpugh** [Darkhax-Minecraft/Bookshelf#81]
I updated to the latest version of Bookshelf and the server crashes on startup with Mekanism present.  Not sure if this is you or Mekanism.

Forge: 2393

Mods:
Bookshelf-1.11.2-2.0.0.388.jar
DarkUtilities-1.11.2-1.2.0.147.jar

Mekanism-1.11.2-9.3.2.307.jar
MekanismGenerators-1.11.2-9.3.2.307.jar
MekanismTools-1.11.2-9.3.2.307.jar

Report: https://gist.github.com/kwpugh/684e10c9fb73614400cd16b8ad912630

**Comment by darkhax** [comment]
This is a mekanism issue. They have known about it for over a month now and have apparently not fixed it yet. https://github.com/aidancbrady/Mekanism/issues/4414
