### ISSUE TITLE
1.11 Multiple Mod Crash

### ISSUE THREAD

**Issue by Mattabase** [Darkhax-Minecraft/Bookshelf#82]
https://goo.gl/LoAC9T
https://goo.gl/LoAC9T

I know you have not posted a 1.11 in a bit, not really sure whos side it is one but it crashes with multiple mods.

**Comment by darkhax** [comment]
Hello, 

Thanks for reporting this issue. Both of these crashes are on the conflicting mods's side. They're making a bad assumption about vanilla code.
