### ISSUE TITLE
Crash To Desktop From Rendering Error

### ISSUE THREAD

**Issue by Laruae** [Darkhax-Minecraft/Bookshelf#83]
Not sure who's issue this actually is, but there are certain items which will cause a crash to desktop when they attempt to render using JEI. Posting this here because a line refers to Bookshelf.

>net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:303)

JEI, Bookshelf, Thermal Expansion, and CodeChickenLib are all referenced in the log attached, however as I do not know which mod is actually causing this, I am posting this at each mod's GitHub issue section.

Thanks!

[Error Log Gist](https://gist.github.com/Laruae/40f6a1d75d96227b0f6c81f12a59d41f)

**Comment by darkhax** [comment]
It's likely neither. Code Chicken Lib and Bookshelf don't mess with the call unless it is an item from our mods.

**Comment by Laruae** [comment]
Great, I appreciate the quick feedback! Just trying to sort this out. Thanks for all your hard work in the modding community!
