### ISSUE TITLE
[1.12] Incorrect MC Version

### ISSUE THREAD

**Issue by NillerMedDild** [Darkhax-Minecraft/Bookshelf#85]
Hey!

I'm afraid the newest version of Bookshelf is marked as compatible with [1.12.1, 1.12.1], so it doesn't work on 1.12.

Minecraft 1.12
Forge 1.12-14.21.1.2443
Bookshelf 1.12.1-2.0.0.422

[Crashlog](https://pastebin.com/1JVEFAAs)

**Comment by MacAttack-UK** [comment]
I'm seeing the same issue too.

My details are the same as op

**Comment by Nexusdog** [comment]
Confirmed. Same details.

**Comment by xbony2** [comment]
beep beep on the confirmation train

**Comment by darkhax** [comment]
Bug is confirmed, will fix ;p

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by darkhax** [comment]
Okay, this should be fixed in https://github.com/Darkhax-Minecraft/Bookshelf/commit/7b32f1d823c3f824ae7dae9c7624c7fbaca0d384 If it still doesn't work let me know.
