### ISSUE TITLE
Improper Version tag on Curse for Bookshelf-1.12.1-2.0.0.422.jar

### ISSUE THREAD

**Issue by BrendanTA** [Darkhax-Minecraft/Bookshelf#86]
I understand this specific version is for 1.12.1 but on Curse you say it also works with 1.12 and when launching it, the message saying you need MC version 1.12 or higher appears.
I just ask you remove that it's compatible with 1.12 if it isn't.
Screenshot of Curse:
[![Screenshot from Gyazo](https://gyazo.com/20e471c56ca9cba2fe7d73c6df23b6a7/raw)](https://gyazo.com/20e471c56ca9cba2fe7d73c6df23b6a7)
Screenshot in-game:
[![Screenshot from Gyazo](https://gyazo.com/8e18ed6958db1eba35ffecf4d1c802a1/raw)](https://gyazo.com/8e18ed6958db1eba35ffecf4d1c802a1)

**Comment by darkhax** [comment]
This was fixed in 2.0.0.424, sorry for not marking that build as a full release.
