### ISSUE TITLE
Messed up version number in Bookshelf 2.1 breaks other mods depending on it

### ISSUE THREAD

**Issue by asiekierka** [Darkhax-Minecraft/Bookshelf#88]
Example: Dark Utilities

**Comment by darkhax** [comment]
Currently moving all my projects to a new Jenkins, so I am fixing build stuff to be more standardized. In this case, the four part build number was a mistake that was meant to be corrected to 3 a long time ago. I will have fixes for all the mods that dep on bookshelf out soon.

**Comment by darkhax** [comment]
Re-oppening this issue to help me track what has/hasn't been fixed.
