### ISSUE TITLE
two Bookshelf APIs - double naming

### ISSUE THREAD

**Issue by walkerjonny** [Darkhax-Minecraft/Bookshelf#9]
Hi, 
there is another API around there that is also called Bookshelf API.
http://minecraft.curseforge.com/projects/bookshelf-api-library
Could you please talk together to find a solution for that double naming issue

**Comment by darkhax** [comment]
Hello, thank you for raising this issue. Our team has been aware of the other mod for some time now, however we have yet to reach out to them to work on a solution. I don't believe there is a need to have two issues for this, so I will close our version of the issue, and continue the discussion on their repository. https://github.com/TeamBR-Modding/Bookshelf/issues/2
