### ISSUE TITLE
JEI Incompatibility | Nullpointer

### ISSUE THREAD

**Issue by Janrupf** [Darkhax-Minecraft/Bookshelf#90]
Hello, im getting a NullPointerExeption when trying to view the crafting recipe in JEI. Looks like ExtraUtils2 is also involved:
[crashlog](https://github.com/Darkhax-Minecraft/Bookshelf/files/1290539/crash-2017-09-10_15.02.09-client.txt)

**Comment by darkhax** [comment]
In this situation Bookshelf is not involved. The issue would be between JEI and EU2. Also 1.10.2 is no longer supported.
