### ISSUE TITLE
User-oriented features not working in 1.12.1

### ISSUE THREAD

**Issue by luckyp3616** [Darkhax-Minecraft/Bookshelf#91]
[latest-log.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/1300342/latest-log.txt)
The bookshelves of the different wood types don't show up and the default config is not dropped in .minecraft/config folder.

**Comment by darkhax** [comment]
The 1.12.1 version of the mod does not have any of the user oriented features. I am not sure if I will be adding them back.

**Comment by luckyp3616** [comment]
That sucks. :(

**Comment by darkhax** [comment]
This will be added in a future mod. I will let you know when I make one here.

**Comment by luckyp3616** [comment]
okay

**Comment by darkhax** [comment]
The attribute fix is now released in [this](https://minecraft.curseforge.com/projects/attributefix) mod.
