### ISSUE TITLE
(1.12.2) Rendering fluids with null flowing sprite

### ISSUE THREAD

**Issue by GlobbyPotato** [Darkhax-Minecraft/Bookshelf#95]
Bookshelf 1.12.2-2.3.523 release
Hi, adding LiquidXP from OpenBlocks into my tank (which renders with the RenderUtils.renderFluid() feature) it missed to render the sides of the fluid, returning this ticking error:

[01:42:17] [main/WARN] [bookshelf]: Attempted to draw a textures quad with no texture!

Not sure about it, quickly searching through the methods it looks like fluids with a null Flowing sprite do not try to replace it with the Still one. Other fluids give no problems.

Thank you for the useful features.

**Comment by darkhax** [comment]
This is a bit of an issue, since a fluid without both textures is not really valid. I have made a new method that allows you to specify the textures to use yourself though. This should help cover your use case.
